version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5434"
    volumes:
    -  \PostgreSQL\13\data
    env_file:
    - docker.env
    environment:
      POSTGRES_PASSWORD: postgres
      

 
