version: "3.8"
services:
  postgres:
    container_name: postgres3
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - /Users/Oluwatamilore/data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
 # pgadmin:
 #   links:
 #   - postgres:postgres2
 #   container_name: pgadmin
 #   image: dpage/pgadmin4
 #   ports:
 #   - "8080:80"
 #   volumes:
#  - /Users/Oluwatamilore/data/pgadmin:/root/.pgadmin
 #   env_file:
   # - docker.env
  #  networks:
  #  - postgres
 
networks:
  postgres:
    driver: bridge